// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp1vqgEgQSNI7QMUhn1DbQO6tTWeI4J_U',
    appId: '1:93017610900:web:458f34f1f7534d1fc4b281',
    messagingSenderId: '93017610900',
    projectId: 'papa-c3673',
    authDomain: 'papa-c3673.firebaseapp.com',
    storageBucket: 'papa-c3673.appspot.com',
    measurementId: 'G-RRPDHX13WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeKsOeBtF1I_Gq3cJtZ12nN0Fy2LXue-4',
    appId: '1:93017610900:android:b9e85c246bb0ae28c4b281',
    messagingSenderId: '93017610900',
    projectId: 'papa-c3673',
    storageBucket: 'papa-c3673.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4f7ywoHYkB2qiUgaTdSZ0ZbOV6hxb_qI',
    appId: '1:93017610900:ios:37c0cb22e4b950fec4b281',
    messagingSenderId: '93017610900',
    projectId: 'papa-c3673',
    storageBucket: 'papa-c3673.appspot.com',
    iosBundleId: 'sn.ept.pic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4f7ywoHYkB2qiUgaTdSZ0ZbOV6hxb_qI',
    appId: '1:93017610900:ios:b67323ef412af8a9c4b281',
    messagingSenderId: '93017610900',
    projectId: 'papa-c3673',
    storageBucket: 'papa-c3673.appspot.com',
    iosBundleId: 'sn.ept.pic.RunnerTests',
  );
}

